<h1 style="text-align: center;">Data Profiling</h1>

## Short explanation
This notebook performs an initial profile of all tables in the football database to understand their structure, size, completeness, uniqueness, value distributions, date coverage, and basic data-quality characteristics. It will also examine key relationships between tables. The findings will later be used to build the project's data catalogue and guide further data exploration and problem definition.

---

### Library Import

In [1]:
import sqlite3
import pandas as pd

## Database import

In [6]:
connection = sqlite3.connect(r"..\Data\database.sqlite")

In [8]:
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", connection)

In [9]:
tables

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

### Data import

In [10]:
country_df = pd.read_sql("SELECT * FROM Country", connection)

In [11]:
country_df.head()

      id     name
0      1  Belgium
1   1729  England
2   4769   France
3   7809  Germany
4  10257    Italy

In [12]:
league_df = pd.read_sql("SELECT * FROM League", connection)

In [13]:
league_df.head()

      id  country_id                    name
0      1           1  Belgium Jupiler League
1   1729        1729  England Premier League
2   4769        4769          France Ligue 1
3   7809        7809   Germany 1. Bundesliga
4  10257       10257           Italy Serie A

In [14]:
player_df = pd.read_sql("SELECT * FROM Player", connection)

In [15]:
player_df.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

In [16]:
player_attributes_df = pd.read_sql("SELECT * FROM Player_Attributes", connection)

In [17]:
player_attributes_df.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [18]:
team_df = pd.read_sql("SELECT * FROM Team", connection)

In [19]:
team_df.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [22]:
team_attributes_df = pd.read_sql("SELECT * FROM Team_Attributes", connection)

In [23]:
team_attributes_df.head()

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

In [24]:
match_df = pd.read_sql("SELECT * FROM Match", connection)

In [25]:
match_df.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

---

## Country Table Profile

In [27]:
country_profile = pd.DataFrame({
    "columns":country_df.columns,
    "Data_type": country_df.dtypes.values,
    "missing_value": country_df.isna().sum().values,
    "missing_percentage": (country_df.isna().mean()*100).values,
    "unique_value":country_df.nunique().values
})

In [28]:
country_profile

  columns Data_type  missing_value  missing_percentage  unique_value
0      id     int64              0                 0.0            11
1    name       str              0                 0.0            11

In [29]:
country_df.shape

(11, 2)

In [30]:
country_df.duplicated().sum()

np.int64(0)

In [37]:
country_df

       id         name
0       1      Belgium
1    1729      England
2    4769       France
3    7809      Germany
4   10257        Italy
5   13274  Netherlands
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

### Evaluation 

The Country table is small, containing 11 records and 2 columns. Both columns are complete, with no missing values, and there are no duplicate rows. Each column contains 11 unique values, indicating that both the country IDs and country names are unique within this table. Overall, the table appears structurally clean based on these basic profiling checks.

---

## League Table Profiling

In [39]:
league_profile = pd.DataFrame({
    "Columns":  league_df.columns,
    "Data_type": league_df.dtypes.values,
    "missing_values": league_df.isna().sum().values,
    "missing_percentages": (league_df.isna().mean()*100).values,
    "uniqe_values": league_df.nunique().values
})

In [40]:
league_profile

      Columns Data_type  missing_values  missing_percentages  uniqe_values
0          id     int64               0                  0.0            11
1  country_id     int64               0                  0.0            11
2        name       str               0                  0.0            11

In [41]:
league_df.shape

(11, 3)

In [42]:
league_df.duplicated().sum()

np.int64(0)

In [43]:
league_df

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

### Evaluation
The League table is small, containing 11 records and 3 columns. It has no missing values or duplicate rows, and all three columns contain 11 unique values. The country_id column provides the foreign-key relationship with the Country table, while each league name is unique. Overall, the table appears clean based on the initial profiling checks.

---

## Player Table Profile

In [44]:
player_profile = pd.DataFrame({
    "Columns":player_df.columns,
    "Data_Type": player_df.dtypes.values,
    "Missing_values": player_df.isna().sum().values,
    "Missing_Percentage": (player_df.isna().mean()*100).values,
    "Unique": player_df.nunique().values
})

In [45]:
player_profile

              Columns Data_Type  Missing_values  Missing_Percentage  Unique
0                  id     int64               0                 0.0   11060
1       player_api_id     int64               0                 0.0   11060
2         player_name       str               0                 0.0   10848
3  player_fifa_api_id     int64               0                 0.0   11060
4            birthday       str               0                 0.0    5762
5              height   float64               0                 0.0      20
6              weight     int64               0                 0.0      50

In [46]:
player_df.shape

(11060, 7)

In [47]:
player_df.duplicated().sum()

np.int64(0)

In [49]:
player_df.head(10)

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
5,6,27316,Aaron Hunt,158138,1986-09-04 00:00:00,182.88,161
6,7,564793,Aaron Kuhl,221280,1996-01-30 00:00:00,172.72,146
7,8,30895,Aaron Lennon,152747,1987-04-16 00:00:00,165.10,139
8,9,528212,Aaron Lennox,206592,1993-02-19 00:00:00,190.50,181
9,10,101042,Aaron Meijers,188621,1987-10-28 00:00:00,175.26,170

### Evaluation
The Player table contains 11,060 records and 7 columns, with no missing values or duplicate rows. The API and FIFA identifiers are unique, while player names contain some repeated values. Overall, the table appears complete and structurally clean based on the initial profiling checks.

---

## Player Attributes profile

In [50]:
player_attributes_profile = pd.DataFrame({
    "Columns":player_attributes_df.columns,
    "Data_types":player_attributes_df.dtypes.values,
    "Missing_values": player_attributes_df.isna().sum().values,
    "Missing_percentage": (player_attributes_df.isna().mean()*100).values,
    "Unique": player_attributes_df.nunique().values
})

In [51]:
player_attributes_profile

                Columns Data_types  Missing_values  Missing_percentage  Unique
0                    id      int64               0            0.000000  183978
1    player_fifa_api_id      int64               0            0.000000   11062
2         player_api_id      int64               0            0.000000   11060
3                  date        str               0            0.000000     197
4        overall_rating    float64             836            0.454402      61
5             potential    float64             836            0.454402      56
6        preferred_foot        str             836            0.454402       2
7   attacking_work_rate        str            3230            1.755645       8
8   defensive_work_rate        str             836            0.454402      19
9              crossing    float64             836            0.454402      95
10            finishing    float64             836            0.454402      97
11     heading_accuracy    float64             836            0.454402      96
12        short_passing    float64             836            0.454402      95
13              volleys    float64            2713            1.474633      93
14            dribbling    float64             836            0.454402      97
15                curve    float64            2713            1.474633      92
16   free_kick_accuracy    float64             836            0.454402      97
17         long_passing    float64             836            0.454402      95
18         ball_control    float64             836            0.454402      93
19         acceleration    float64             836            0.454402      86
20         sprint_speed    float64             836            0.454402      85
21              agility    float64            2713            1.474633      81
22            reactions    float64             836            0.454402      78
23              balance    float64            2713            1.474633      81
24           shot_power    float64             836            0.454402      96
25              jumping    float64            2713            1.474633      79
26              stamina    float64             836            0.454402      84
27             strength    float64             836            0.454402      82
28           long_shots    float64             836            0.454402      96
29           aggression    float64             836            0.454402      91
30        interceptions    float64             836            0.454402      96
31          positioning    float64             836            0.454402      95
32               vision    float64            2713            1.474633      97
33            penalties    float64             836            0.454402      94
34              marking    float64             836            0.454402      95
35      standing_tackle    float64             836            0.454402      95
36       sliding_tackle    float64            2713            1.474633      94
37            gk_diving    float64             836            0.454402      93
38          gk_handling    float64             836            0.454402      90
39           gk_kicking    float64             836            0.454402      97
40       gk_positioning    float64             836            0.454402      94
41          gk_reflexes    float64             836            0.454402      92

In [52]:
player_attributes_df.shape

(183978, 42)

In [53]:
player_attributes_df.duplicated().sum()

np.int64(0)

In [54]:
player_attributes_df.head().T

,0,1,2,3,4
id,1,2,3,4,5
player_fifa_api_id,218353,218353,218353,218353,218353
player_api_id,505942,505942,505942,505942,505942
date,2016-02-18 00:00:00,2015-11-19 00:00:00,2015-09-21 00:00:00,2015-03-20 00:00:00,2007-02-22 00:00:00
overall_rating,67.0,67.0,62.0,61.0,61.0
potential,71.0,71.0,66.0,65.0,65.0
preferred_foot,right,right,right,right,right
attacking_work_rate,medium,medium,medium,medium,medium
defensive_work_rate,medium,medium,medium,medium,medium
crossing,49.0,49.0,49.0,48.0,48.0
finishing,44.0,44.0,44.0,43.0,43.0
heading_accuracy,71.0,71.0,71.0,70.0,70.0
short_passing,61.0,61.0,61.0,60.0,60.0
volleys,44.0,44.0,44.0,43.0,43.0
dribbling,51.0,51.0,51.0,50.0,50.0
curve,45.0,45.0,45.0,44.0,44.0
free_kick_accuracy,39.0,39.0,39.0,38.0,38.0
long_passing,64.0,64.0,64.0,63.0,63.0
ball_control,49.0,49.0,49.0,48.0,48.0
acceleration,60.0,60.0,60.0,60.0,60.0
sprint_speed,64.0,64.0,64.0,64.0,64.0
agility,59.0,59.0,59.0,59.0,59.0
reactions,47.0,47.0,47.0,46.0,46.0
balance,65.0,65.0,65.0,65.0,65.0
shot_power,55.0,55.0,55.0,54.0,54.0
jumping,58.0,58.0,58.0,58.0,58.0
stamina,54.0,54.0,54.0,54.0,54.0
strength,76.0,76.0,76.0,76.0,76.0
long_shots,35.0,35.0,35.0,34.0,34.0
aggression,71.0,71.0,63.0,62.0,62.0
interceptions,70.0,70.0,41.0,40.0,40.0
positioning,45.0,45.0,45.0,44.0,44.0
vision,54.0,54.0,54.0,53.0,53.0
penalties,48.0,48.0,48.0,47.0,47.0
marking,65.0,65.0,65.0,62.0,62.0
standing_tackle,69.0,69.0,66.0,63.0,63.0
sliding_tackle,69.0,69.0,69.0,66.0,66.0
gk_diving,6.0,6.0,6.0,5.0,5.0
gk_handling,11.0,11.0,11.0,10.0,10.0
gk_kicking,10.0,10.0,10.0,9.0,9.0
gk_positioning,8.0,8.0,8.0,7.0,7.0
gk_reflexes,8.0,8.0,8.0,7.0,7.0

### Evalutation
The Player_Attributes table contains 183,978 records and 42 columns. No duplicate rows were identified, and the id column is unique. However, several attribute columns contain missing values, with the extent varying across columns. These missing values will be investigated and addressed later during the data-cleaning stage.

---

## Team Table Profile

In [55]:
team_profile = pd.DataFrame({
    "Columns":team_df.columns,
    "Data_type":team_df.dtypes.values,
    "missing_values":team_df.isna().sum().values,
    "Missing_percentages":(team_df.isna().mean()*100).values,
    "Unique":team_df.nunique().values
})

In [56]:
team_profile

            Columns Data_type  missing_values  Missing_percentages  Unique
0                id     int64               0              0.00000     299
1       team_api_id     int64               0              0.00000     299
2  team_fifa_api_id   float64              11              3.67893     285
3    team_long_name       str               0              0.00000     296
4   team_short_name       str               0              0.00000     259

In [57]:
team_df.shape

(299, 5)

In [58]:
team_df.duplicated().sum()

np.int64(0)

In [60]:
team_df.head(10)

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB
5   6         8635             229.0     RSC Anderlecht             AND
6   7         9991             674.0           KAA Gent             GEN
7   8         9998            1747.0          RAEC Mons             MON
8   9         7947               NaN      FCV Dender EH             DEN
9  10         9985             232.0  Standard de Liège             STL

### Evaluation 
The Team table contains 299 records and 5 columns, with no duplicate rows. Most fields are complete, although team_fifa_api_id contains 11 missing values. The API identifiers and team names are not all unique, which is worth keeping in mind for later relationship and data-quality checks.

---

## Team Attributes Profile

In [61]:
team_attributes_profile = pd.DataFrame({
    "Columns":team_attributes_df.columns,
    "Data_type":team_attributes_df.dtypes.values,
    "missing_values":team_attributes_df.isna().sum().values,
    "Missing_percentages":(team_attributes_df.isna().mean()*100).values,
    "Unique":team_attributes_df.nunique().values
})

In [62]:
team_attributes_profile

,Columns,Data_type,missing_values,Missing_percentages,Unique
0,id,int64,0,0.000000,1458
1,team_fifa_api_id,int64,0,0.000000,285
2,team_api_id,int64,0,0.000000,288
3,date,str,0,0.000000,6
4,buildUpPlaySpeed,int64,0,0.000000,57
5,buildUpPlaySpeedClass,str,0,0.000000,3
6,buildUpPlayDribbling,float64,969,66.460905,49
7,buildUpPlayDribblingClass,str,0,0.000000,3
8,buildUpPlayPassing,int64,0,0.000000,58
9,buildUpPlayPassingClass,str,0,0.000000,3
10,buildUpPlayPositioningClass,str,0,0.000000,2
11,chanceCreationPassing,int64,0,0.000000,50
12,chanceCreationPassingClass,str,0,0.000000,3
13,chanceCreationCrossing,int64,0,0.000000,56
14,chanceCreationCrossingClass,str,0,0.000000,3
15,chanceCreationShooting,int64,0,0.000000,57
16,chanceCreationShootingClass,str,0,0.000000,3
17,chanceCreationPositioningClass,str,0,0.000000,2
18,defencePressure,int64,0,0.000000,48
19,defencePressureClass,str,0,0.000000,3
20,defenceAggression,int64,0,0.000000,47
21,defenceAggressionClass,str,0,0.000000,3
22,defenceTeamWidth,int64,0,0.000000,43
23,defenceTeamWidthClass,str,0,0.000000,3
24,defenceDefenderLineClass,str,0,0.000000,2

In [63]:
team_attributes_df.shape

(1458, 25)

In [64]:
team_attributes_df.duplicated().sum()

np.int64(0)

In [66]:
team_attributes_df.head(5).T

,0,1,2,3,4
id,1,2,3,4,5
team_fifa_api_id,434,434,434,77,77
team_api_id,9930,9930,9930,8485,8485
date,2010-02-22 00:00:00,2014-09-19 00:00:00,2015-09-10 00:00:00,2010-02-22 00:00:00,2011-02-22 00:00:00
buildUpPlaySpeed,60,52,47,70,47
buildUpPlaySpeedClass,Balanced,Balanced,Balanced,Fast,Balanced
buildUpPlayDribbling,NaN,48.0,41.0,NaN,NaN
buildUpPlayDribblingClass,Little,Normal,Normal,Little,Little
buildUpPlayPassing,50,56,54,70,52
buildUpPlayPassingClass,Mixed,Mixed,Mixed,Long,Mixed
buildUpPlayPositioningClass,Organised,Organised,Organised,Organised,Organised
chanceCreationPassing,60,54,54,70,53
chanceCreationPassingClass,Normal,Normal,Normal,Risky,Normal
chanceCreationCrossing,65,63,63,70,48
chanceCreationCrossingClass,Normal,Normal,Normal,Lots,Normal
chanceCreationShooting,55,64,64,70,52
chanceCreationShootingClass,Normal,Normal,Normal,Lots,Normal
chanceCreationPositioningClass,Organised,Organised,Organised,Organised,Organised
defencePressure,50,47,47,60,47
defencePressureClass,Medium,Medium,Medium,Medium,Medium
defenceAggression,55,44,44,70,47
defenceAggressionClass,Press,Press,Press,Double,Press
defenceTeamWidth,45,54,54,70,52
defenceTeamWidthClass,Normal,Normal,Normal,Wide,Normal
defenceDefenderLineClass,Cover,Cover,Cover,Cover,Cover

### Evaluation
The Team_Attributes table contains 1,458 records and 25 columns, with no duplicate rows. Most columns are complete, with buildUpPlayDribbling having approximately 66% missing values. The remaining columns contain no missing values. The id column is unique, while the other identifiers contain repeated values.

---

## Match Profile

In [67]:
match_profile = pd.DataFrame({
    "Columns":match_df.columns,
    "Data_type":match_df.dtypes.values,
    "missing_values":match_df.isna().sum().values,
    "Missing_percentages":(match_df.isna().mean()*100).values,
    "Unique":match_df.nunique().values
})

In [71]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

match_profile

              Columns Data_type  missing_values  Missing_percentages  Unique
0                  id     int64               0             0.000000   25979
1          country_id     int64               0             0.000000      11
2           league_id     int64               0             0.000000      11
3              season       str               0             0.000000       8
4               stage     int64               0             0.000000      38
5                date       str               0             0.000000    1694
6        match_api_id     int64               0             0.000000   25979
7    home_team_api_id     int64               0             0.000000     299
8    away_team_api_id     int64               0             0.000000     299
9      home_team_goal     int64               0             0.000000      11
10     away_team_goal     int64               0             0.000000      10
11     home_player_X1   float64            1821             7.009508       3
12     home_player_X2   float64            1821             7.009508       9
13     home_player_X3   float64            1832             7.051850       8
14     home_player_X4   float64            1832             7.051850       7
15     home_player_X5   float64            1832             7.051850       9
16     home_player_X6   float64            1832             7.051850       9
17     home_player_X7   float64            1832             7.051850       9
18     home_player_X8   float64            1832             7.051850       9
19     home_player_X9   float64            1832             7.051850       9
20    home_player_X10   float64            1832             7.051850       9
21    home_player_X11   float64            1832             7.051850       6
22     away_player_X1   float64            1832             7.051850       3
23     away_player_X2   float64            1832             7.051850       8
24     away_player_X3   float64            1832             7.051850       8
25     away_player_X4   float64            1832             7.051850       8
26     away_player_X5   float64            1832             7.051850       9
27     away_player_X6   float64            1832             7.051850       9
28     away_player_X7   float64            1832             7.051850       9
29     away_player_X8   float64            1832             7.051850       9
30     away_player_X9   float64            1833             7.055699       9
31    away_player_X10   float64            1833             7.055699       9
32    away_player_X11   float64            1839             7.078794       6
33     home_player_Y1   float64            1821             7.009508       3
34     home_player_Y2   float64            1821             7.009508       2
35     home_player_Y3   float64            1832             7.051850       2
36     home_player_Y4   float64            1832             7.051850       2
37     home_player_Y5   float64            1832             7.051850       5
38     home_player_Y6   float64            1832             7.051850       6
39     home_player_Y7   float64            1832             7.051850       6
40     home_player_Y8   float64            1832             7.051850       7
41     home_player_Y9   float64            1832             7.051850       6
42    home_player_Y10   float64            1832             7.051850       7
43    home_player_Y11   float64            1832             7.051850       4
44     away_player_Y1   float64            1832             7.051850       2
45     away_player_Y2   float64            1832             7.051850       1
46     away_player_Y3   float64            1832             7.051850       2
47     away_player_Y4   float64            1832             7.051850       3
48     away_player_Y5   float64            1832             7.051850       5
49     away_player_Y6   float64            1832             7.051850       7
50     away_player_Y7   float64            1832             7.051850       7
51     away_player_Y8   float64            1832             7.051850       7
52     away_player_Y9   float64            1833             7.055699       7
53    away_player_Y10   float64            1833             7.055699       6
54    away_player_Y11   float64            1839             7.078794       4
55      home_player_1   float64            1224             4.711498     906
56      home_player_2   float64            1315             5.061781    2414
57      home_player_3   float64            1281             4.930906    2375
58      home_player_4   float64            1323             5.092575    2606
59      home_player_5   float64            1316             5.065630    2769
60      home_player_6   float64            1325             5.100273    3798
61      home_player_7   float64            1227             4.723046    3422
62      home_player_8   float64            1309             5.038685    4076
63      home_player_9   float64            1273             4.900112    4114
64     home_player_10   float64            1436             5.527541    3642
65     home_player_11   float64            1555             5.985604    2890
66      away_player_1   float64            1234             4.749990     926
67      away_player_2   float64            1278             4.919358    2504
68      away_player_3   float64            1293             4.977097    2470
69      away_player_4   float64            1321             5.084876    2657
70      away_player_5   float64            1335             5.138766    2884
71      away_player_6   float64            1313             5.054082    3930
72      away_player_7   float64            1235             4.753840    3620
73      away_player_8   float64            1341             5.161862    4249
74      away_player_9   float64            1328             5.111821    4319
75     away_player_10   float64            1441             5.546788    3891
76     away_player_11   float64            1554             5.981754    3040
77               goal       str           11762            45.275030   13225
78             shoton       str           11762            45.275030    8464
79            shotoff       str           11762            45.275030    8464
80         foulcommit       str           11762            45.275030    8466
81               card       str           11762            45.275030   13777
82              cross       str           11762            45.275030    8466
83             corner       str           11762            45.275030    8465
84         possession       str           11762            45.275030    8420
85              B365H   float64            3387            13.037453     121
86              B365D   float64            3387            13.037453      72
87              B365A   float64            3387            13.037453     115
88                BWH   float64            3404            13.102891     237
89                BWD   float64            3404            13.102891     133
90                BWA   float64            3404            13.102891     261
91                IWH   float64            3459            13.314600     147
92                IWD   float64            3459            13.314600      73
93                IWA   float64            3459            13.314600     159
94                LBH   float64            3423            13.176027     129
95                LBD   float64            3423            13.176027      72
96                LBA   float64            3423            13.176027     128
97                PSH   float64           14811            57.011432     948
98                PSD   float64           14811            57.011432     665
99                PSA   float64           14811            57.011432    1475
100               WHH   float64            3408            13.118288     125
101               WHD   float64            3408            13.118288      78
102               WHA   float64            3408            13.118288     136
103               SJH   float64            8882            34.189153     137
104               SJD   float64            8882            34.189153      79
105               SJA   float64            8882            34.189153     132
106               VCH   float64            3411            13.129836     160
107               VCD   float64            3411            13.129836      82
108               VCA   float64            3411            13.129836     151
109               GBH   float64           11817            45.486739     159
110               GBD   float64           11817            45.486739      84
111               GBA   float64           11817            45.486739     172
112               BSH   float64           11818            45.490589     101
113               BSD   float64           11818            45.490589      59
114               BSA   float64           11818            45.490589      96

In [69]:
match_df.shape

(25979, 115)

In [70]:
match_df.duplicated().sum()

np.int64(0)

### Evaluation 
The remaining fields mainly represent pre-match betting odds from different bookmakers for home win, draw, and away win outcomes. Several bookmaker groups have substantial missing values, with some fields missing for around 45% of matches. Importantly, the Match table does not contain an explicit classification target, so a target may need to be derived from the available match-result information. This will be considered later when defining the ML problem.

---

# Profiling Summary

Initial profiling of all seven database tables has been completed. The main structural characteristics, missing values, duplicates, and key observations have been documented.

Detailed table metadata and profiling findings are available in:

`docs/data_catalog/`

The original field and abbreviation reference is available in:

`docs/football_data_reference_notes.txt`

The data catalogue should be used as the project-specific reference for the database, while the Football-Data reference notes should be used to interpret documented field abbreviations and betting-related variables.

Further data-quality checks, relationship validation, and target definition will be carried out in the next stages of the project.